Exercise 1: Arrays in Financial Analytics (Banking Sector)

In [104]:
import numpy as np

In [106]:
# 1. Use NumPy to create a 2D array representing transaction volumes for 4 branches over 6 months.
# Each row represents a branch, and each column a month. (4 marks)

transVolumes = np.array([
                         [100, 250, 320, 400, 570, 620],
                         [706, 870, 909, 1050, 1500, 2000],
                         [650, 570, 460, 350, 290, 1000],
                         [2000, 1050, 1000, 950, 810, 709]
                        ])

In [108]:
# 2. Calculate the total transactions per branch. (4 marks)

branches = ['Branch 1', 'Branch 2', 'Branch 3', 'Branch 4']
totalTrans = transVolumes.sum(axis=1)
for add, branch in zip(totalTrans, branches):
    print(f"The total transactions of {branch} is: {add}")

The total transactions of Branch 1 is: 2260
The total transactions of Branch 2 is: 7035
The total transactions of Branch 3 is: 3320
The total transactions of Branch 4 is: 6519


In [120]:
# 3. Identify the branch with the highest total transactions. (4 marks)

highTotalTrans = np.argmax(totalTrans)
print(f"{branches[1]} has the highest total transaction of {totalTrans[highTotalTrans]}")

Branch 2 has the highest total transaction of 7035


In [122]:
# 4. Compute the average monthly transaction volume across all branches. (4 marks)

averageTransac = transVolumes.mean(axis=1)
for average, branch in zip(averageTransac, branches):
    print(f"The average monthly transaction volume of {branch} is: {average}")

The average monthly transaction volume of Branch 1 is: 376.6666666666667
The average monthly transaction volume of Branch 2 is: 1172.5
The average monthly transaction volume of Branch 3 is: 553.3333333333334
The average monthly transaction volume of Branch 4 is: 1086.5


In [124]:
# 5. Reshape the array to a 3x8 format and explain the implications of reshaping in this context. (4marks)

reshapedArray = transVolumes.reshape(3, 8)

In [126]:
print(reshapedArray)

[[ 100  250  320  400  570  620  706  870]
 [ 909 1050 1500 2000  650  570  460  350]
 [ 290 1000 2000 1050 1000  950  810  709]]


Exercise 2: Lists in Logistics Management (Supply Chain Sector)

In [167]:
# 1. Create a list of 10 delivery routes, each represented as a string. (4 marks)

deliveRoutes = list((
                    'Maseno Unversity', 'Kisumu', 'Luanda', 'Nyalenda area', 'Nairobi',
                    'Mombasa', 'Nakuru', 'Kariobangi', 'Kiambu', 'Migori'
                    ))

In [169]:
# 2. Append a new route and remove a discontinued one. (4 marks)

deliveRoutes.append('Kilifi')

deliveRoutes.remove(deliveRoutes[7])

In [171]:
# 3. Sort the list alphabetically and reverse it. (4 marks)

deliveRoutes.sort(reverse=True)

In [173]:
# 4. Count how many routes start with the letter “N”. (4 marks)

count_N = sum(route.startswith('N') for route in deliveRoutes)

print(f"Number of routes satrting with letter 'N' is: {count_N}")

Number of routes satrting with letter 'N' is: 3


In [177]:
# 5. Use list comprehension to create a new list of routes longer than 10 characters. (4 marks)

long_routes = list((route for route in deliveRoutes if len(route) > 10))
print(long_routes)

['Nyalenda area', 'Maseno Unversity']


Exercise 3: Tuples in Medical Records (Healthcare Sector)

In [221]:
# 1. Create a tuple for a patient containing: (Name, Age, Blood Pressure, Heart Rate). (4 marks)

patient = tuple(('Steve', 20, '120/80', 72))

In [223]:
# 2. Access and print the patient’s age and heart rate. (4 marks)

print(f"{patient[0]} is {patient[1]} years old with {patient[3]} heart rate")

Steve is 20 years old with 72 heart rate


In [231]:
# 4. Convert the tuple to a list, update the heart rate, and convert it back to a tuple. (4 marks)

convertedToList = list(patient)
convertedToList[3] = 75
convertedToTuple = tuple(convertedToList)
print(convertedToTuple)

('Steve', 20, '120/80', 75)


In [237]:
# 5. Create a tuple of 5 patients and write code to extract all names. (4 marks)

patients = (
            ('Steve', 20, '120/80', 75),
            ('Elsa', 20, '121/80', 72),
            ('Charles', 21, '122/80', 70),
            ('Sam', 23, '123/80', 77),
            ('Rael', 19, '124/80', 78)
)

for patient in patients:
    name, age, bp, hr = patient
    print(f"{name} is {age} years old having {bp} blood pressure with {hr} heart rate")

Steve is 20 years old having 120/80 blood pressure with 75 heart rate
Elsa is 20 years old having 121/80 blood pressure with 72 heart rate
Charles is 21 years old having 122/80 blood pressure with 70 heart rate
Sam is 23 years old having 123/80 blood pressure with 77 heart rate
Rael is 19 years old having 124/80 blood pressure with 78 heart rate


Exercise 4: Dictionaries in E-Commerce (Retail Sector)

In [270]:
# 1. Create a dictionary with 5 products as keys and their stock quantities as values. (4 marks)

products = dict([
                ('Cat6 cable', 9),
                ('Redmi 13C', 10),
                ('RJ 45 Connectors', 5),
                ('Mouse', 9),
                ('Monitors', 20),
])

In [278]:
# 2. Add a new product and update the quantity of an existing one. (4 marks)

products['Keyboard'] = 20
products.update({'Redmi 13C': 20})

In [302]:
# 3. Write a function to return products with stock less than 10. (4 marks)

def LessStock():
    return {product: qty for product, qty in products.items() if qty < 10}

LessStock()

{'Cat6 cable': 9, 'RJ 45 Connectors': 5, 'Mouse': 9}

In [306]:
# 4. Delete a discontinued product and display the updated dictionary. (4 marks)

products.pop('Monitors')
print(products)

{'Cat6 cable': 9, 'Redmi 13C': 20, 'RJ 45 Connectors': 5, 'Mouse': 9, 'Keyboard': 20}


In [308]:
# 5. Use .items() to loop through and print each product with its quantity. (4 marks)

for product, qty in products.items():
    print(f"{product} has {qty} left")

Cat6 cable has 9 left
Redmi 13C has 20 left
RJ 45 Connectors has 5 left
Mouse has 9 left
Keyboard has 20 left
